# Generated by Django 4.0.6 on 2022-07-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('dining', 'Dining'), ('experience', 'Experience'), ('general', 'General')], max_length=100),
        ),
    ]
